ALTER TABLE "User" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "locationUpdatedAt" TIMESTAMP(3);

ALTER TABLE "Technician" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Technician" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "Technician" ADD COLUMN "locationUpdatedAt" TIMESTAMP(3);

ALTER TABLE "Complaint" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Complaint" ADD COLUMN "longitude" DOUBLE PRECISION;
